// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];
  
  constructor( 
    private servEditora: ControleEditoraService, 
    private servLivro: ControleLivrosService
  ) {}

  ngOnInit(){
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivro.obterLivros().then((livros) => this.livros = livros);
  }

  public excluir = (codigo: string) => {
    this.servLivro.excluir(codigo).then(
      () => this.livros = this.servLivro.obterLivros().then((livros) => this.livros = livros)
    )
    t
  }

  public obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main>
    <div class="container">
        
    <h1 class="titulo">Catálago de Livros</h1>
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>
                    {{livro.titulo}}
                    <br>
                    <button class="btn botao" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td>{{livro.resumo}}</td>
                <td>{{obterNome(livro.codEditora)}}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{autor}}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
    </div>
</main>

// clientes/livros-react/src/LivroLista.js
import { useEffect, useState } from "react";
import ControleEditora from "./controle/ControleEditora";
import ControleLivros from "./controle/ControleLivros";

function LivroLista() {
  const controleLivros = new ControleLivros();
  const controleEditora = new ControleEditora();
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);
  
  useEffect(() => {
    const obterTodos = async () => {
      const livros = await controleLivros.obterLivros().then((livros) => {
        setLivros(livros);
        setCarregado(true);
      });
    };
    obterTodos();
  }, [controleLivros]);

  const excluir = async (codigo) => {
    await controleLivros.excluir(codigo);
    setCarregado(false);
  };
  
  return (
    <main>
      <div className="container">
        <h1>Catalogo de Livros</h1>
        <table>
          <thead className="cabecalho">
            <tr>
              <th className="titulos">Título</th>
              <th className="titulos">Resumo</th>
              <th className="titulos">Editora</th>
              <th className="titulos">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro
                key={index}
                livro={livro}
                controleLivros={controleLivros}
                controleEditora={controleEditora}
                excluir={excluir}
              />
            ))}
          </tbody>
        </table>
      </div>
    </main>
  );
}
export default LivroLista;

function LinhaLivro(props) {
  let nomeEditora = props.controleEditora.getNomeEditora(props.livro.codEditora);
  return (
    <tr className="item">
      <td>
        {props.livro.titulo}
        <br />
        <button onClick={() => props.excluir(props.livro.codigo)} className="botao">
          Excluir
        </button>
      </td>
      <td>{props.livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {props.livro.autores.map((autor) => (
            <li key={autor}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}
