// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component} from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent {
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  constructor(
    private servEditora: ControleEditoraService,
    private servLivro: ControleLivrosService,
    private router: Router
    ) {}
  
  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
  }

  public incluir = () => {
    this.livro.codEditora = Number(this.livro.codEditora);
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivro.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/');
    })
    
  }
}
<main>
    <div class="container">
        <h1 class="titulo">Dados Livros</h1>
    <form (submit)= incluir() ngNativeValidate>
        <div class="mb-3 form-check">
            <label class="form-label">Título</label>
            <input type="text" class="form-control" [(ngModel)]="livro.titulo" name="Titulo" required>
        </div>
        <div class="mb-3 form-check">
            <label class="form-label">Resumo</label>
            <textarea cols="30" rows="3" class="form-control" [(ngModel)]="livro.resumo" name="Resumo"></textarea>
        </div>
        <div class="mb-3 form-check">
            <label class="form-label">Editora</label>
            <select class="form-select" [(ngModel)]="livro.codEditora" name="Editora">
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
            </select>
        </div>
        <div class="mb-3 form-check">
            <label class="form-label">Autores</label>
            <textarea cols="30" rows="3" class="form-control" [(ngModel)]="autoresForm" name="Autores"></textarea>
            <button type="submit" class="btn botao">Salvar Dados</button>
        </div>
    </form>
    </div>  
</main>

// clientes/livros-next/pages/LivroDados.tsx
import type {NextPage} from 'next'; 
import styles from '../styles/Home.module.css'
import Livro from  '../classes/modelo/Livro';
import {useState} from 'react';
import {useRouter} from 'next/router';
import ControleEditora from '../classes/controle/ControleEditora';
import ControleLivros from '../classes/controle/ControleLivros';
import {Menu} from '../componentes/Menu'
import Head from 'next/head';


const LivroDados: NextPage = () => {
    let controleLivro = new ControleLivros();
    let controleEditora = new ControleEditora();
    let Router = useRouter();
    let opcoes = controleEditora.getEditoras().map(editora => ({value: editora.codEditora, text: editora.nome}));
    let [titulo, setTitulo] = useState('');
    let [resumo, setResumo] = useState('');
    let [autores, setAutores] = useState('');
    let [codEditora, setCodEditora] = useState(opcoes[0].value);
    let tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(event.target.value));
    }
    let incluir = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        const livro: Livro = {
            codigo: "",
            titulo: titulo,
            resumo: resumo,
            autores: autores.split('\n'),
            codEditora: codEditora,
        };
        const incluindo = await controleLivro.incluir(livro);
        if (incluindo) Router.push('/LivroLista');
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
            </Head>
            <Menu />
            <main>
                <h1>Dados do Livros</h1>
                <form onSubmit={incluir}>
                     <div className="form-group">
                        <label htmlFor="titulo">Título:</label>
                        <input type="text" className="form-control" onChange={(event) => setTitulo(event.target.value)}></input>
                    </div>
                    <div className="form-group">
                        <label htmlFor="resumo">Resumo:</label>
                        <textarea cols={30} rows={3} onChange={(event) => setResumo(event.target.value)} className="form-control"></textarea>   
                    </div>
                    <div className="form-group">
                        <label htmlFor="codEditora">Editora:</label>
                        <select
                            id="codEditora"
                            className="form-control"
                            value={codEditora}
                            onChange={tratarCombo}
                        >
                            {opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>
                                    {opcao.text}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className="form-group">
                        <label htmlFor="autores">Autores:</label>
                        <textarea cols={30} rows={3} onChange={(event) => setAutores(event.target.value)} className="form-control"></textarea>
                    </div>
                    <div className="form-group">
                        <button type="submit" className='botao'>Salvar Dados</button>
                    </div>
                </form>
            </main>
        </div>
    )
};

export default LivroDados;
